// app
export const APP_SETROUTEBEFORESIGNIN_SET = 'APP_SETROUTEBEFORESIGNIN_SET'
export const APP_SETCOOKIESACCEPTED_SET = 'APP_SETCOOKIESACCEPTED_SET'
export const APP_LOGIN_SET = 'APP_LOGIN_SET'
export const APP_LOGOUT_SET = 'APP_LOGOUT_SET'
export const APP_FETCHUSER_LOAD = 'APP_FETCHUSER_LOAD'
export const APP_FETCHUSER_SUCCEED = 'APP_FETCHUSER_SUCCEED'
export const APP_FETCHUSER_FAIL = 'APP_FETCHUSER_FAIL'

// app_metadata
export const APP_FETCHBLOCKCHAINLIST_SUCCEED = 'APP_FETCHBLOCKCHAINLIST_SUCCEED'
export const APP_FETCHTAGLIST_SUCCEED = 'APP_FETCHTAGLIST_SUCCEED'
